### ISSUE TITLE
New SQL Code

### ISSUE THREAD

**Issue by IXIRPOS** [msbatal/PHP-PDO-Database-Class#3]
Hello, how can I run the following SQL code?

`SELECT sum(((u.alisfiyati/b.oran)*(m.cikismiktari))) as maliyetim FROM menuler v, urunler u, menuicerikleri m, birimler b where u.id=m.urunid and u.birim=b.id and v.id=m.menuid and v.id=7`

**Comment by msbatal** [comment]
Hello. You should use the rawQuery method for complex SQL statements.

You can run your query as a simple statement:

`$select = $db->rawQuery("SELECT SUM(((u.alisfiyati/b.oran)*(m.cikismiktari))) AS maliyetim FROM menuler v, urunler u, menuicerikleri m, birimler b WHERE (u.id=m.urunid AND u.birim=b.id AND v.id=m.menuid AND v.id=7)")->run();`

or as a prepared statement (bind parameters):

`$select = $db->rawQuery("SELECT SUM(((u.alisfiyati/b.oran)*(m.cikismiktari))) AS maliyetim FROM menuler v, urunler u, menuicerikleri m, birimler b WHERE (u.id=m.urunid AND u.birim=b.id AND v.id=m.menuid AND v.id=?)", ['7'])->run();`

**Comment by msbatal** [comment]
Hello. You should use the rawQuery method for complex SQL statements.

You can run your query as a simple statement:

`$select = $db->rawQuery("SELECT SUM(((u.alisfiyati/b.oran)*(m.cikismiktari))) AS maliyetim FROM menuler v, urunler u, menuicerikleri m, birimler b WHERE (u.id=m.urunid AND u.birim=b.id AND v.id=m.menuid AND v.id=7)")->run();`

or as a prepared statement (bind parameters):

`$select = $db->rawQuery("SELECT SUM(((u.alisfiyati/b.oran)*(m.cikismiktari))) AS maliyetim FROM menuler v, urunler u, menuicerikleri m, birimler b WHERE (u.id=m.urunid AND u.birim=b.id AND v.id=m.menuid AND v.id=?)", ['7'])->run();`

**For more:** [https://github.com/msbatal/PHP-PDO-Database-Class#raw-sql-queries](url)
